/*Malika Sharma
 *Culminating
 *28/01/2020
 *
 */

/**
 *
 * @author VIASVS
 */
public class form22 extends javax.swing.JFrame {
     //declare method variables
    static double num1, num2, num3, num4, num5, num6, num7, num8,num9;
    /**
     * Creates new form form22
     */
    public form22() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        diameterText = new javax.swing.JLabel();
        textDiameter = new javax.swing.JTextField();
        tittle1 = new javax.swing.JLabel();
        tittle2 = new javax.swing.JLabel();
        tittle3 = new javax.swing.JLabel();
        tittle4 = new javax.swing.JLabel();
        dealText = new javax.swing.JLabel();
        optionText = new javax.swing.JTextField();
        subtotalDisplay = new javax.swing.JLabel();
        taxesDisplay = new javax.swing.JLabel();
        GrandTotalDisplay = new javax.swing.JLabel();
        GoButton1 = new javax.swing.JButton();
        subtotalText = new javax.swing.JLabel();
        taxesText = new javax.swing.JLabel();
        grandtotalText = new javax.swing.JLabel();
        GrandTotalDisplay1 = new javax.swing.JLabel();
        GrandTotalDisplay2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        tittle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tittle.setText("Pizza Order ");

        diameterText.setText("Please Enter the diameter of your pizza");

        tittle1.setText("Choose your pizza deal");

        tittle2.setText("1.) Two Toppings with Breadsticks $22.99");

        tittle3.setText("2.) Three Toppings with 10 Chicken Wings $24.99");

        tittle4.setText("3.) Four Topping with Potato Wedges and six cans of pop $33.99 ");

        dealText.setText("Choose Your Deal");

        GoButton1.setText("Go");
        GoButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoButton1ActionPerformed(evt);
            }
        });

        subtotalText.setText("Subtotal");

        taxesText.setText("Taxes");

        grandtotalText.setText("Grandtotal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(tittle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(tittle1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dealText))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tittle2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(optionText, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(diameterText)
                                                .addComponent(tittle3)
                                                .addComponent(tittle4)
                                                .addComponent(textDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(GrandTotalDisplay)
                                                .addGap(18, 18, 18)
                                                .addComponent(GrandTotalDisplay1)
                                                .addGap(18, 18, 18)
                                                .addComponent(GrandTotalDisplay2)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(70, 70, 70))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(taxesText)
                                        .addGap(18, 18, 18)
                                        .addComponent(taxesDisplay)
                                        .addGap(99, 99, 99)))
                                .addComponent(GoButton1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(grandtotalText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subtotalText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(subtotalDisplay)
                        .addGap(139, 139, 139)))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittle)
                .addGap(32, 32, 32)
                .addComponent(diameterText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tittle1)
                    .addComponent(dealText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tittle2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tittle3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tittle4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grandtotalText)
                    .addComponent(subtotalText)
                    .addComponent(subtotalDisplay))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GrandTotalDisplay)
                            .addComponent(GrandTotalDisplay1)
                            .addComponent(GrandTotalDisplay2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxesText)
                            .addComponent(taxesDisplay))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(GoButton1)
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     // Methods for option 1
    public static double addAndOut (double num1, double num2, double num3, double num4,double num5){
        double subtotal1 = (num1 + num3 + num2 + num1 + num5 * num4) ;
        return subtotal1;
     } 
      public static double multAndOut (double num1, double num2, double num3, double num4, double num8, double num5){
        double taxes1 = (num1 + num3 + num2 + num1 + num5 *num4)*  num8 ;
        return taxes1;
     }
      public static double AndOut (double num1, double num2, double num3, double num4, double num8, double num5){
        double Grandtotal1 = (num1 + num3 + num2 + num1 + num5 * num4) + (num1 + num3 + num2 + num1 + num5 *num4)*  num8 ;
        return Grandtotal1;
      } 
      
     
      
       
   //Methods for option 2 
     
     public static double muAndOut (double num1, double num2, double num3, double num4, double num6){
        double subtotal2 =  (num1 + num3 + num2 + num1 + num6 * num4);
        return subtotal2;
     } 
     public static double mAndOut (double num1, double num2, double num3, double num4,double num6,  double num8){
        double taxes2 = (num1 + num3 + num2 + num1 + num6 * num4) *num8;
        return taxes2;
     } 
     public static double mulOut (double num1, double num2, double num3, double num4,double num6,  double num8){
        double Grandtotal2 = (num1 + num3 + num2 + num1 + num6 * num4) *num8;
        return Grandtotal2 = (num1 + num3 + num2 + num1 + num6 * num4) + (num1 + num3 + num2 + num1 + num6 * num4) *num8; 
     } 
     
      
     
     //Methods for option 3
     public static double Out (double num1, double num2, double num3, double num4, double num7){
        double subtotal3 =  (num1 + num3 + num2 + num1 + num7 * num4);
        return subtotal3;
     } 
     public static double adAndOut (double num1, double num2, double num3, double num4, double num8,double num7){
        double taxes3 = (num1 + num3 + num2 + num1 + num7 * num4) * num8;
        return taxes3;
     } 
     public static double adAdOut (double num1, double num2, double num3, double num4, double num8,double num7){
        double taxes3 = (num1 + num3 + num2 + num1 + num7 * num4) + (num1 + num3 + num2 + num1 + num7 * num4) * num8;
        return taxes3;
     } 
   
     
      
    private void GoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoButton1ActionPerformed
        //Declare user input Values
        double diameter = Double.parseDouble(textDiameter.getText());
        double option = Double.parseDouble(optionText.getText());
        
         {
        //Values for each variable
        num1 = (double) diameter;
        num2 = (double) 0.99; 
        num3 = (double) 0.75; 
        num4 = (double) 0.50; 
        num5 = (double) 22.99; 
        num6 = (double) 24.99; 
        num7 = (double) 33.99; 
        num8= (double) 0.13; 
        num9=(double) 13.0; 
         } 
       //Call each method + All totals that will be outputted 
        { 
        if (option ==1)
          subtotalDisplay.setText("" + addAndOut(num1,num2,num3,num4,num5));
         taxesDisplay.setText("" + multAndOut(num1,num2, num3,num4,num8,num5));
         GrandTotalDisplay.setText("" + AndOut(num1,num2,num3,num4,num8,num5)); 
      
         
        }   
        { 
        if (option ==2)
         subtotalDisplay.setText("" + muAndOut(num1,num2,num3,num4,num6));
        taxesDisplay.setText("" + mAndOut(num1,num2, num3,num4,num8,num6)); 
        GrandTotalDisplay1.setText("" + mulOut (num1, num2,  num3, num4,num6,num8)); 
       
         } 
        { 
        if (option ==3)
          subtotalDisplay.setText("" + Out(num1,num2,num3,num4,num7));
         taxesDisplay.setText("" + adAndOut(num1,num2, num3,num4,num8,num7));
         GrandTotalDisplay2.setText("" + adAdOut(num1,num2, num3,num4,num8,num7)); 
         
        }    
            
    }//GEN-LAST:event_GoButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form22().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoButton1;
    private javax.swing.JLabel GrandTotalDisplay;
    private javax.swing.JLabel GrandTotalDisplay1;
    private javax.swing.JLabel GrandTotalDisplay2;
    private javax.swing.JLabel dealText;
    private javax.swing.JLabel diameterText;
    private javax.swing.JLabel grandtotalText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField optionText;
    private javax.swing.JLabel subtotalDisplay;
    private javax.swing.JLabel subtotalText;
    private javax.swing.JLabel taxesDisplay;
    private javax.swing.JLabel taxesText;
    private javax.swing.JTextField textDiameter;
    private javax.swing.JLabel tittle;
    private javax.swing.JLabel tittle1;
    private javax.swing.JLabel tittle2;
    private javax.swing.JLabel tittle3;
    private javax.swing.JLabel tittle4;
    // End of variables declaration//GEN-END:variables
}
